apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: exchange-pvc
  namespace: personal
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-storage-class