name: Build, Test & Deploy Production

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      # Get current package.json Version
      - name: Get current package version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.1.0
        
      - name: Build Docker Image
        id: build-image
        run: docker build -t raphy02/exchange:${{ steps.package-version.outputs.current-version}} .
